language: python
dist: trusty

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=pylint
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

cache:
  directories:
    - $HOME/.cache/pip

# setup gopass
before_install:
  - wget -q -O- https://api.bintray.com/orgs/gopasspw/keys/gpg/public.key | sudo apt-key add -
  - echo "deb https://dl.bintray.com/gopasspw/gopass trusty main" | sudo tee /etc/apt/sources.list.d/gopass.list
  - sudo apt-get update
  - sudo apt-get install -y gopass
  - gpg --trust-model always ./travis/sample_key.gpg
  - gpg --import ./travis/sample_key.gpg
  - gopass --yes init

# command to install dependencies
install:
  - pip install -U tox
  - pip install .
#- pip install -r requirements.txt
# command to run tests
script:
  - tox --develop
  # Prevent truncated output.
  - sleep 5